<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\RelationshipFix.Domain\RelationshipFix.Domain.csproj" />
    <ProjectReference Include="..\..\src\RelationshipFix.DataContracts\RelationshipFix.DataContracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="FsCheck.Xunit.v3" />
    <PackageReference Include="Shouldly" />
  </ItemGroup>
</Project>
